#!/usr/bin/env node

const { Command } = require('commander');
const fs = require('fs');
const path = require('path');

const program = new Command();
program
  .name('md-a11y-auditor')
  .description('Audit Markdown for WCAG accessibility issues')
  .version('1.0.0');

program
  .argument('[files...]', 'Markdown files to audit')
  .option('-l, --license <key>', 'Pro license key', 'DEMO')
  .option('-f, --format <fmt>', 'table|json|csv|pdf', 'table')
  .action(async (files, options) => {
    const format = options.format;
    const isPro = ['json', 'csv', 'pdf'].includes(format);
    if (isPro && options.license !== 'DEMO-PRO') {
      console.error('❌ Pro formats (json/csv/pdf) require license key. Buy: https://gumroad.stub/l/md-a11y-pro ($19)');
      process.exit(1);
    }

    const contents = [];
    if (files.length === 0) {
      // stdin
      const stdinContent = fs.readFileSync(0, 'utf8');
      contents.push({content: stdinContent, name: 'stdin.md'});
    } else {
      for (let file of files) {
        let content;
        if (file === '-') {
          content = fs.readFileSync(0, 'utf8');
        } else {
          content = fs.readFileSync(file, 'utf8');
        }
        contents.push({content, name: path.basename(file)});
      }
    }

    let allIssues = [];
    for (let {content, name} of contents) {
      const issues = auditMdRegex(content, name);
      allIssues.push(...issues);
    }

    if (format === 'table') {
      console.table(allIssues.map(i => ({
        file: i.file,
        type: i.type,
        line: i.line,
        details: i.details
      })));
    } else if (format === 'json') {
      console.log(JSON.stringify(allIssues, null, 2));
    } else if (format === 'csv') {
      console.log('file,type,line,details');
      for (let i of allIssues) {
        console.log(`"${i.file}","${i.type}",${i.line},"${i.details.replace(/"/g,'""')}"`);
      }
    } else if (format === 'pdf') {
      await generatePdf(allIssues);
    }

    if (allIssues.length === 0) {
      console.log('✅ No accessibility issues found!');
    }
  });

function auditMdRegex(content, filename) {
  const issues = [];
  const lines = content.split(/\\r?\\n/);
  let currentHeadingLevel = 0;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    // Headings
    const headMatch = line.match(/^(\\s*)(#{1,6})\\s+(.*)/);
    if (headMatch) {
      const level = headMatch[2].length;
      if (level < currentHeadingLevel) {
        issues.push({
          file: filename,
          type: 'heading_regression',
          line: i + 1,
          details: `Heading level ${level} lower than previous ${currentHeadingLevel}`
        });
      } else if (level > currentHeadingLevel + 1) {
        issues.push({
          file: filename,
          type: 'heading_skip',
          line: i + 1,
          details: `Skipped levels from ${currentHeadingLevel || 1} to ${level}`
        });
      }
      currentHeadingLevel = level;
      continue;
    }

    // Images
    const imgMatches = [...line.matchAll(/!\\[(.*?)\\]\\(([^)]+)\\)/g)];
    for (let match of imgMatches) {
      const alt = match[1].trim();
      if (!alt || alt === '' || alt === '[]') {
        issues.push({
          file: filename,
          type: 'missing_alt',
          line: i + 1,
          details: 'Image missing descriptive alt text'
        });
      }
    }

    // Links
    const linkMatches = [...line.matchAll(/\\[(.*?)\\]\\(([^)]+)\\)/g)];
    for (let match of linkMatches) {
      const text = match[1].toLowerCase().trim();
      const badPhrases = ['click here', 'here', 'this link', 'link', 'read more'];
      if (badPhrases.some(p => text.includes(p))) {
        issues.push({
          file: filename,
          type: 'bad_link_text',
          line: i + 1,
          details: `Non-descriptive link text: "${match[1]}"`
        });
      }
    }
  }

  return issues;
}

async function generatePdf(issues) {
  const puppeteer = require('puppeteer');
  const browser = await puppeteer.launch({ headless: 'new' });
  const page = await browser.newPage();
  let html = `
    <!DOCTYPE html>
    <html>
    <head><title>MD A11y Audit</title><style>
      table { border-collapse: collapse; width: 100%; }
      th, td { border: 1px solid #ddd; padding: 8px; }
      th { background-color: #f2f2f2; }
    </style></head>
    <body>
      <h1>Markdown Accessibility Audit Report</h1>
      <p>Generated by md-a11y-auditor-cli</p>
      <table>
        <thead><tr><th>File</th><th>Type</th><th>Line</th><th>Details</th></tr></thead>
        <tbody>
  `;
  for (let issue of issues) {
    html += `<tr><td>${issue.file}</td><td>${issue.type}</td><td>${issue.line}</td><td>${issue.details}</td></tr>`;
  }
  html += `
        </tbody>
      </table>
    </body>
    </html>
  `;
  await page.setContent(html, { waitUntil: 'networkidle0' });
  const pdfBuffer = await page.pdf({ format: 'A4', printBackground: true });
  fs.writeFileSync('md-a11y-report.pdf', pdfBuffer);
  console.log('📄 Report saved: md-a11y-report.pdf');
  await browser.close();
}

program.parse(process.argv);
